apiVersion: core.gardener.cloud/v1
kind: Subnet
metadata:
  name: sub1234
spec:
  ID: sub1234
  networkGlobalID: customer1
  region: [EU-West]
  availabilityZone: [A]
  type: IPv4
  cidr: 10.12.34.0/24
  subnetParentID: topsubnet