apiVersion: core.gardener.cloud/v1
kind: Subnet
metadata:
  name: sub1235
spec:
  ID: sub1235
  type: IPv4
  cidr: 10.12.35.0/24
  networkGlobalID: customer1
  partitionID: Frankfurt
  subnetParentID: topsubnet