apiVersion: core.gardener.cloud/v1
kind: Subnet
metadata:
  name: sub2
spec:
  ID: sub2
  type: IPv4
  cidr: 10.12.35.0/28
  networkGlobalID: customer1
  partitionID: Frankfurt
  subnetParentID: topsubnet