apiVersion: core.gardener.cloud/v1
kind: Subnet
metadata:
  name: subnet2
spec:
  ID: sub1234
  Type: IPv4
  cidr: 10.12.34.0/24
  networkGlobalID: customer2
  PartitionID: Frankfurt
  subnetParentId: topsubnet