apiVersion: core.gardener.cloud/v1
kind: Subnet
metadata:
  name: subv6-2
spec:
  ID: sub2
  type: IPv6
  cidr: 2001:db8:1002::/48
  networkGlobalID: customer1
  partitionID: Frankfurt
  subnetParentID: subv6-1