apiVersion: core.gardener.cloud/v1
kind: Subnet
metadata:
  name: tbn1
spec:
  ID: tbn1
  Type: IPv4
  cidr: 10.12.34.0/25
  networkGlobalID: customer1
  partitionID: Frankfurt
  subnetParentID: sub1234