apiVersion: core.gardener.cloud/v1
kind: Subnet
metadata:
  name: topsubnet
spec:
  ID: topsubnet
  networkGlobalID: customer1
  region: [EU-West]
  availabilityZone: [A, B, C]
  type: IPv4
  cidr: 10.12.0.0/16
  