# permissions for end users to view networkglobals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkglobal-viewer-role
rules:
- apiGroups:
  - core.core.gardener.cloud
  resources:
  - networkglobals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.core.gardener.cloud
  resources:
  - networkglobals/status
  verbs:
  - get
